### PR TITLE
fix of the selection of one file outside the "Bulk select" when initi…

### PR DESCRIPTION
**Pull request by 4KDA**
fix of the selection of one file outside the "Bulk select" when initial lmm in multi-select mode

### CODE REVIEW

**Comment by ctf0** [comment]
can u elaborate more, am not sure why this is needed

**Comment by 4KDA** [comment]
This applies to multi select mode. Now, when initializing lmm in multi select mode, files are selected only by clicking the "bulk select" button, that is, if you want to add only 1 file, you still need to click "bulk select", and with this fix 1 file can be selected without clicking "bulk select".

**Comment by ctf0** [comment]
because if u want to select only one file then u shouldnt use the multi select option, the multi select isnt a one solution fits all.

u will just have to find ur way around with the current implementation.

**Comment by 4KDA** [comment]
if the user depending on the situation is necessary to choose 1 or more files (in the same gallery is the situation when the need to the existing add more only one file) - you propose add to this situation 2 button initialization lmm? why you do not want to do this method Universal? it can somewhere cause an error?

**Comment by ctf0** [comment]
doing what u want create issues for another part of the package, so again **create your own implementation**

**Comment by 4KDA** [comment]
I did not think that this fix could create problems for the package. It is a pity that this is so.

**Pull request closed without merging**
